simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name ='accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/',views.SignUp.as_view(), name='signup')
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/', views.UserPost.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.Homepage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls', namespace='groups')),

]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Star Social</title>

  {# BOOTSTRAP4 #}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  {# GOOGLE FONTS API #}
  <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet"> {# MASTER CSS #}
  {# <link rel="stylesheet" href="{% static " simplesocial/css/master.css " %}"> #}

  {# FONT AWESOME CDN #}
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
</head>

<body>


  <nav class="navbar navbar-expand-md navbar-dark bg-success">
    <a class="navbar-brand" href="#">Star Social</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse conatiner-fluid" id="navbarNavDropdown">

      <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}

        <li class="nav-item">
          <a href="{% url 'posts:all' %}" class="nav-link">Post</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'groups:all' %}" class="nav-link">Groups</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'groups:create' %}" class="nav-link">Create Group</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url 'groups:all' %}" class="nav-link">Groups</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'accounts:signup'%}" class="nav-link">Sign Up</a>
        </li>
      {% endif %}

      </ul>
    </div>
  </nav>
  <div class="container mycontent">
    {% block content %}

    {% endblock %}

  </div>
</body>

</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to Star Social</h1>
{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}

{% block content %}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}